# Generated by Django 5.2.12 on 2026-04-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_procurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='approvalrequest',
            new_name='ai_procurem_status_e20121_idx',
            old_name='ai_procurem_approval_status_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='demandforecast',
            new_name='ai_procurem_part_id_73bb60_idx',
            old_name='ai_procurem_forecast_part_created_idx',
        ),
        migrations.RenameIndex(
            model_name='fewshotmemory',
            new_name='ai_procurem_part_ca_480591_idx',
            old_name='ai_procurem_memory_category_idx',
        ),
        migrations.RenameIndex(
            model_name='fewshotmemory',
            new_name='ai_procurem_outcome_6c1fec_idx',
            old_name='ai_procurem_memory_quality_idx',
        ),
        migrations.RenameIndex(
            model_name='fewshotmemory',
            new_name='ai_procurem_usage_c_335c6c_idx',
            old_name='ai_procurem_memory_usage_idx',
        ),
        migrations.RenameIndex(
            model_name='pipelineexecution',
            new_name='ai_procurem_part_id_d03797_idx',
            old_name='ai_procurem_part_id_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='pipelineexecution',
            new_name='ai_procurem_status_2ac380_idx',
            old_name='ai_procurem_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pipelineexecution',
            new_name='ai_procurem_created_018d4c_idx',
            old_name='ai_procurem_created_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierevaluation',
            new_name='ai_procurem_supplie_bc11e9_idx',
            old_name='ai_procurem_eval_supplier_part_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierreliabilityscore',
            new_name='ai_procurem_supplie_730077_idx',
            old_name='ai_procurem_reliability_supplier_part_idx',
        ),
        migrations.RenameIndex(
            model_name='supplierreliabilityscore',
            new_name='ai_procurem_last_up_06e01a_idx',
            old_name='ai_procurem_reliability_updated_idx',
        ),
    ]
